#!/usr/bin/env bash
#
# Registers everything Readermost needs inside the local Mattermost: an admin,
# a friend to argue with, a team, the shared channel, and the OAuth app. Writes
# readermost.local.toml with the results.
#
# Safe to re-run: existing objects are reused rather than duplicated.

cd "$(dirname "$0")/.."
source dev/lib.sh

command -v jq >/dev/null || die "jq is not installed — run this inside 'nix develop'"

api() {
  local method="$1" path="$2" body="${3:-}" token="${4:-}"
  local args=(-fsS -X "$method" -H "Content-Type: application/json")
  [[ -n "$token" ]] && args+=(-H "Authorization: Bearer ${token}")
  [[ -n "$body" ]] && args+=(-d "$body")
  curl "${args[@]}" "${MATTERMOST_URL}/api/v4${path}"
}

log "waiting for mattermost"
wait_for "${MATTERMOST_URL}/api/v4/system/ping" "mattermost" 120

# The very first account created on a fresh Mattermost becomes system admin.
log "creating admin user (${MM_ADMIN_USER})"
api POST /users "$(jq -nc \
  --arg e "$MM_ADMIN_EMAIL" --arg u "$MM_ADMIN_USER" --arg p "$MM_ADMIN_PASS" \
  '{email:$e, username:$u, password:$p}')" >/dev/null 2>&1 \
  || log "admin already exists, continuing"

log "logging in"
LOGIN_HEADERS=$(mktemp)
trap 'rm -f "$LOGIN_HEADERS"' EXIT
curl -fsS -D "$LOGIN_HEADERS" -o /dev/null \
  -H "Content-Type: application/json" \
  -d "$(jq -nc --arg u "$MM_ADMIN_USER" --arg p "$MM_ADMIN_PASS" \
        '{login_id:$u, password:$p}')" \
  "${MATTERMOST_URL}/api/v4/users/login" \
  || die "could not log in as ${MM_ADMIN_USER}"

TOKEN=$(grep -i '^token:' "$LOGIN_HEADERS" | tr -d '\r' | awk '{print $2}')
[[ -n "$TOKEN" ]] || die "mattermost returned no session token"

ADMIN_ID=$(api GET /users/me "" "$TOKEN" | jq -r .id)

log "creating friend user (${MM_FRIEND_USER})"
api POST /users "$(jq -nc \
  --arg e "$MM_FRIEND_EMAIL" --arg u "$MM_FRIEND_USER" --arg p "$MM_FRIEND_PASS" \
  '{email:$e, username:$u, password:$p}')" "$TOKEN" >/dev/null 2>&1 \
  || log "friend already exists, continuing"
FRIEND_ID=$(api GET "/users/username/${MM_FRIEND_USER}" "" "$TOKEN" | jq -r .id)

log "creating team (${MM_TEAM})"
TEAM_ID=$(api GET "/teams/name/${MM_TEAM}" "" "$TOKEN" 2>/dev/null | jq -r .id || true)
if [[ -z "$TEAM_ID" || "$TEAM_ID" == "null" ]]; then
  TEAM_ID=$(api POST /teams "$(jq -nc --arg n "$MM_TEAM" \
    '{name:$n, display_name:"Readermost", type:"O"}')" "$TOKEN" | jq -r .id)
fi

for member in "$ADMIN_ID" "$FRIEND_ID"; do
  api POST "/teams/${TEAM_ID}/members" \
    "$(jq -nc --arg t "$TEAM_ID" --arg u "$member" '{team_id:$t, user_id:$u}')" \
    "$TOKEN" >/dev/null 2>&1 || true
done

log "creating shared channel (${MM_CHANNEL})"
CHANNEL_ID=$(api GET "/teams/${TEAM_ID}/channels/name/${MM_CHANNEL}" "" "$TOKEN" 2>/dev/null | jq -r .id || true)
if [[ -z "$CHANNEL_ID" || "$CHANNEL_ID" == "null" ]]; then
  CHANNEL_ID=$(api POST /channels "$(jq -nc --arg t "$TEAM_ID" --arg n "$MM_CHANNEL" \
    '{team_id:$t, name:$n, display_name:"Reader Shared", type:"O"}')" "$TOKEN" | jq -r .id)
fi

for member in "$ADMIN_ID" "$FRIEND_ID"; do
  api POST "/channels/${CHANNEL_ID}/members" \
    "$(jq -nc --arg u "$member" '{user_id:$u}')" "$TOKEN" >/dev/null 2>&1 || true
done

log "registering the OAuth application"
# Reuse an existing app so re-running does not pile up registrations, but a
# fresh secret is only shown at creation time — so recreate if we have none.
EXISTING=$(api GET "/oauth/apps?per_page=200" "" "$TOKEN" \
  | jq -r --arg n "Readermost (local)" '.[] | select(.name == $n) | .id' | head -1)

if [[ -n "$EXISTING" ]]; then
  log "removing previous OAuth app so a usable secret can be issued"
  api DELETE "/oauth/apps/${EXISTING}" "" "$TOKEN" >/dev/null 2>&1 || true
fi

OAUTH=$(api POST /oauth/apps "$(jq -nc --arg cb "${READERMOST_URL}/auth/callback" \
  '{name:"Readermost (local)",
    description:"Local development",
    callback_urls:[$cb],
    homepage:"http://localhost:8080",
    is_trusted:true}')" "$TOKEN") \
  || die "could not create the OAuth app — is EnableOAuthServiceProvider on?"

CLIENT_ID=$(jq -r .id <<<"$OAUTH")
CLIENT_SECRET=$(jq -r .client_secret <<<"$OAUTH")

[[ -n "$CLIENT_ID" && "$CLIENT_ID" != "null" ]] || die "no client id returned"

log "writing ${CONFIG_FILE}"
cat > "$CONFIG_FILE" <<TOML
# Generated by dev/bootstrap.sh — local development only.
# Regenerate with: dev/bootstrap.sh

listen_addr   = ":${READERMOST_PORT}"
public_url    = "${READERMOST_URL}"
database_path = "dev/readermost.dev.db"
session_ttl   = "720h"

encryption_key = "$(openssl rand -base64 32 2>/dev/null || head -c 32 /dev/urandom | base64)"

[mattermost]
url                 = "${MATTERMOST_URL}"
oauth_client_id     = "${CLIENT_ID}"
oauth_client_secret = "${CLIENT_SECRET}"
shared_channel_id   = "${CHANNEL_ID}"

[miniflux]
url            = "${MINIFLUX_URL}"
admin_username = "${MINIFLUX_ADMIN_USER}"
admin_password = "${MINIFLUX_ADMIN_PASS}"
TOML

log "done"
cat <<SUMMARY

  Readermost   ${READERMOST_URL}
  Mattermost   ${MATTERMOST_URL}
  Miniflux     ${MINIFLUX_URL}

  Sign in as   ${MM_ADMIN_USER} / ${MM_ADMIN_PASS}
  or as        ${MM_FRIEND_USER} / ${MM_FRIEND_PASS}   (use a private window)

  Shared channel: ~${MM_CHANNEL}  (${CHANNEL_ID})

Start it with:

  go run ./cmd/readermost --config ${CONFIG_FILE}

SUMMARY
